version: "3.5"

services:


  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: nccu
      MONGO_INITDB_ROOT_PASSWORD: mis
      MONGO_INITDB_DATABASE: linemessage
    container_name: MongoDB_Container
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    container_name: MongoDB-GUI_Container
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: nccu
      ME_CONFIG_MONGODB_ADMINPASSWORD: mis
      ME_CONFIG_MONGODB_URL: mongodb://nccu:mis@mongo:27017/
